desihub/desiutil

py/desiutil/install/desi_install.py

Apparently Python's tarfile library does not autodetect .tar.gz files.
Fixes #7.

Don't assume tarfile can autodetect gz files.

---

doc/changes.rst
doc/desiInstall.rst
py/desiutil/funcfits.py
py/desiutil/git.py
py/desiutil/install.py
py/desiutil/modules.py
py/desiutil/setup.py
py/desiutil/stats.py
py/desiutil/test/t/desiInstall_configuration.ini
py/desiutil/test/test_funcfits.py
py/desiutil/test/test_install.py
py/desiutil/test/test_stats.py

This PR allows certain hard-coded values in desiInstall to be augmented or overridden with an INI-style configuration file.  This fixes #4, and would allow us to quickly adapt the desiInstall configuration without changing the code or cutting a new tag.  For example, this allows
* Adding a new software package to the existing, hard-coded list of known products.
* Changing the list of NERSC hosts for the purposes of cross installing (when new NERSC systems are added or old ones go away).
There are also some code and documentation clean-ups in this PR.

Allow optional overrides of desiInstall configuration

---

doc/changes.rst
py/desiutil/io.py
py/desiutil/test/test_io.py

Method to convert a Python object (often a dict) into a yaml-valid 
object.  Mainly to be used for writing to yaml.
Am pretty sure this is Python3 compatible (passes Travis and some
of my own tests), but I am not fully confident of all cases.
Creates a new module (io.py)
Updated changes.rst
Added unittest

Method to 'yamilify' a Python object

---

doc/api.rst
doc/changes.rst
py/desiutil/depend.py
py/desiutil/test/test_depend.py

This PR adds a `desiutil.depend` module with utilities for working with code dependencies stored in FITS headers.  The code name and the code version are stored in pairs of keywords, similar to how table columns are defined.  e.g.
```
DEPNAM00 = 'numpy'
DEPVER00 = '1.11'
DEPNAM01 = 'desiutil'
DEPVER01 = '1.4.1'
```
The functions and Dependencies class provide convenience wrappers to loop over they keywords looking for a particular dependency and adding a new dependency version to next available DEPNAMnn/DEPVERnn.
Examples:
```
>>> import desiutil
>>> from desiutil import depend
>>> import astropy
>>> from astropy.io import fits
>>> 
>>> hdr = fits.Header()
>>> depend.setdep(hdr, 'desiutil', desiutil.__version__)
>>> depend.setdep(hdr, 'astropy', astropy.__version__)
>>> depend.getdep(hdr, …
```

add desiutil.depend module

---

py/desiutil/depend.py
py/desiutil/test/test_depend.py

Adds `desiutil.depend.add_dependencies(header, module_names=None)` function that will loop over known possible DESI dependencies and add them to the header only if they have already been imported by the code.  This assumes that if the module is loaded, it was loaded for a good reason and should be listed as a dependency.  Conversely, if a module wasn't loaded by the time you got far enough to write a file then it wasn't actually a dependency for that file.  This saves individual packages or I/O routines from having to maintain their own list of what might have been a dependency.  `module_names` allows the user to override with a different list of module names to check.  This does not go so far as trying to automagically detect every loaded module that isn't part of the standard library. …

add add_dependencies()

---

doc/changes.rst
py/desiutil/modules.py

This PR fixes #46 by searching for a top-level `/python` directory.

Python directory

---

doc/api.rst
doc/changes.rst
py/desiutil/install.py
py/desiutil/plots.py
py/desiutil/test/test_install.py

This PR enables desiInstall to install repos in desihub even if they aren't previously added to the known_products list.  e.g. successfully installing the new surveysim repo:
```
desi@edison01[1020]$ desiInstall surveysim 0.1.1
desiInstall [desiutil.install.DesiInstall.get_options] Log - WARNING: The environment variable LANG is not set!
desiInstall [desiutil.install.DesiInstall.get_product_version] Log - WARNING: guessing surveysim is at https://github.com/desihub/surveysim
desiInstall [desiutil.install.DesiInstall.get_product_version] Log - WARNING: Add location to desiutil.install.known_products if that is incorrect
desi@edison01[1023]$ module avail surveysim
--------------------------------------------------------- /global/common/edison/contrib/desi/modulefiles …
```

enable installation of new desihub repos

---

py/desiutil/sklearn.py

This PR adds a new module semi-arbitrarily called ```sklearn``` which contains the ```GaussianMixtureModel``` class taken from sklearn.  This class was previously in ```desisim.templates``` but now it is needed by both the template-generating code *and* ```desitarget.mock.io``` (as part of https://github.com/desihub/desitarget/issues/136; see also https://github.com/desihub/desitarget/issues/106 and [dr2_mag_distributions.ipynb](https://github.com/desihub/desitarget/blob/master/doc/dr2_mag_distributions.ipynb).
I called it sklearn in case we decide to pull in other functionality without introducing an unnecessary dependence but we can easily change the name.
[Thanks to @dkirkby, who originally pulled this piece out of sklearn.]

add new sklearn.GaussianMixtureModel functionality

---

.travis.yml
doc/changes.rst
py/desiutil/test/test_log.py
py/desiutil/test/test_plots.py
py/desiutil/test/test_sklearn.py

This PR:
1. Demonstrates how to run `coverage` in Python 3.5.  In many cases we are still running coverage tests in 2.7.
2. Runs the Travis `build_sphinx` test in Python 3.5.
3. Adds Python 3.6 tests to the .travis.yml file, because we might as well get ready for that.
4. Increases test coverage on some modules.
Item 1 is the most important, but in general, this is pretty non-controversial stuff. I will merge within 24 hours, unless there are specific requests for reviews.

Travis 3.6

---

py/desiutil/test/test_install.py

This PR fixes the desiutil installation test at NERSC.  It was previously failing because it was picking `/global/common/edison/contrib/desi/code/desiutil/master` as the installation location, and then erroring because that already existed.
The test already included some logic to unset `$DESI_PRODUCT_ROOT` to try to avoid this, but that was unsuccessful because if that isn't set then the installation logic defaults to using `/global/common/edison/contrib/desi/code` anyway.
The workaround here is to test installing a fake branch "test-blat-foo".  An alternate workaround would have been to set `$DESI_PRODUCT_ROOT` to some other location instead of unsetting it.
Note: I purposefully didn't update changes.rst since this seems too small to bother cluttering the human-friendly log of important …

fix install test at NERSC

---

.travis.yml
doc/changes.rst
doc/index.rst
py/desiutil/plots.py
py/desiutil/test/test_plots.py
requirements.txt

This PR:
* Closes #60 
* Adds documentation to distinguish between required and optional dependencies.
* Improves documentation of plots.py module.
* Improves test coverage of plots.py module.
* Temporarily removes an experimental macOS test.

Minimal requirements

---

doc/changes.rst
py/desiutil/modules.py
py/desiutil/test/test_modules.py

This PR fixes desiInstall for cori, but i'm not sure it is the best solution (see below)
Previously desiInstall looked for `modulecmd` in `/opt/modules/${MODULE_VERSION}/bin/modulecmd`.  That is true for some but not all versions of modules at NERSC; in particular it is not true for the current version of modules on cori (3.2.10.5).  This PR works around that by also checking `/opt/cray/pe/modules/${MODULE_VERSION}/bin/modulecmd` instead.
For consideration: I think it would be better for this whole section to use `distutils.spawn.find_executable('modulecmd')` rather than special casing the likely location on multiple machines.  So I'm offering the minimal fix in this PR, but perhaps we should use `find_executable` or similar instead.

fix desiInstall on cori

---

py/desiutil/test/test_svn.py

This PR deals with a few bugs in `test_svn.py` (not the `desiutil.svn` module itself).  At NERSC, we discovered that the system versions of `svn` and `svnadmin` can be out of sync (see #75).  This PR checks that these utilities have the same version.  It also catches a few cases where tests would run anyway even if the subversion infrastructure wasn't working.

Fix svn tests

---

doc/changes.rst
py/desiutil/test/__init__.py
py/desiutil/test/test_install.py
py/desiutil/test/test_setup.py

This PR
* Fixes #78 
* Fixes #79 
* Does not change the actual desiutil API in anyway.  The only changes are to the test suite.
This PR can be merged at any time, but there is no need to immediately tag desiutil, since there are no API changes.

Fix NERSC environment test failures

---

doc/changes.rst
py/desiutil/brick.py
py/desiutil/test/test_brick.py

Fails with:
======================================================================
ERROR: test_brick_radec_scalar (desiutil.test.test_brick.TestBrick)
Test scalar to brick RA,Dec conversion.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/dstn/desiutil/py/desiutil/test/test_brick.py", line 258, in test_brick_radec_scalar
ra,dec = b.brick_radec(0., 0.)
File "/Users/dstn/desiutil/py/desiutil/brick.py", line 284, in brick_radec
xra = self._center_ra[irow][icol]
TypeError: only integer scalar arrays can be converted to a scalar index
----------------------------------------------------------------------
irow and icol are numpy arrays of integers with one element each.

add unit test demonstrating failure of Brick.brick_radec() on scalar inputs

---

doc/changes.rst
py/desiutil/brick.py
py/desiutil/test/test_brick.py

Fixes some implicit assumptions that bricksize evenly divides 180 degrees:
* don't assume the last brick is at the north pole (Dec=90)
* avoid Dec edges exceeding 90 degrees
* avoid Dec array indexing error
* fix handling of the equator in computing required number of bricks in a row

Fix bugs that caused bricks to be larger than bricksize.

---

doc/changes.rst
py/desiutil/log.py
py/desiutil/test/test_census.py
py/desiutil/test/test_depend.py
py/desiutil/test/test_install.py
py/desiutil/test/test_log.py

This PR closes #66:
* Calls to `get_logger()` return different loggers, depending on log level and other configuration details, so that a logger of level `DEBUG` does not interfere with a logger of level `INFO`.
* Creates a default logger with default level `INFO` at import time.  This is available as `desiutil.log.log`, *e.g.*:
```python
from desiutil.log import log
log.info('Information.')
```

Independent log levels

---

doc/changes.rst
py/desiutil/data/desiutil.module
py/desiutil/install.py
py/desiutil/test/test_install.py

This PR attempts to fix #104 at least for future installs by checking that during the bootstrap process, desiInstall is installed with an explicit desiconda version, not "current".
In theory, it would be possible to reject any attempt to use desiInstall if, internally, it cannot find an explicit desiconda version, but I have not implemented this.  I can if that is desired.  If we go down this road though, we may want to consider simply eliminating the 'current' symlink entirely, so that it is impossible not to choose an explicit version.
In addition, the desiutil.module file is added to the internal structure of the desiutil Python package so that it is available even if the etc/ directory is not installed, which it won't be, because we no longer copy the full package contents on install. …

Python executable path

---

doc/changes.rst
py/desiutil/sklearn.py

The sklearn data model changed recently.  This simple PR supports both old and newer versions of `sklearn.mixture.GaussianMixture` which is used in a variety of places in `desihub`.

update to more recent sklearn.mixture.GaussianMixture keywords

---

doc/changes.rst
py/desiutil/install.py

This PR updates `desiInstall` so that it removes write permission after an installation to protect against accidental changes later.  It purposefully removes write permission even from the installing user (e.g. `desi`).
Previously `desiInstall` would run `fix_permissions.sh` which leaves write-permission alone, leaving us in a state where any desi collaborator could accidentally delete a code installation.
I'd like to get this (or equivalent) into a new tag to include in the 18.9 release so that future installations will be safe from accidental overwrite.
changes.rst still needs to be updated, after this has a PR number and @weaverba137 approves of the approach implemented here.

remove write permission after installation

---

doc/changes.rst
py/desiutil/plots.py

Draw the ecliptic in `plots.init_sky()`.  Shown as a dotted red line by default, but can use a different color or turned off using the `ecliptic_color` parameter.

Add ecliptic plane to all-sky plots

---

doc/changes.rst
py/desiutil/dust.py
py/desiutil/test/test_dust.py

This PR moves `ext_odonnell` and `ext_ccm` from `desispec.dustextinction` into `desiutil.dust` (which already had SFD E(B-V) code) in preparation for both desitarget and desispec using these extinction laws.
I think this is what we agreed to on the last DESI data telecon, but mentioning @julienguy  @moustakas @geordie666 @weaverba137 for comment if they disagree.

add desiutil.dust.ext_odonnell and ext_ccm from desispec

---

doc/changes.rst
py/desiutil/setup.py
setup.py

This PR closes #130, providing a mechanism to auto-generate Sphinx API files.
Examples:
* Generate `doc/api.rst` from scratch: `python setup.py api`
* Overwrite an existing `doc/api.rst` file: `python setup.py api --overwrite`
* Generate a *new* api file to compare with an existing file: `python setup.py api --api doc/new_api.rst`
I've tested this on desiutil itself, where it generated a document byte-for-byte identical to the existing api file, and also on desispec, where it found only minor differences.

Auto-generate API files

---

py/desiutil/test/test_plots.py

This PR works around issue #134 where tests of `desiutil.plots.plot_slices` were blowing memory.  The problem came from calling `plot_slices` without an `axis` argument, in which case it uses `plt.gca()`.  Apparently the test was picking up the plot axes from a previous test that was leftover in plt.gca, and generating some corrupted plot that would blow memory when you try to save it.  Now the test generates its own clean axes to use.
Regardless of this "fix", I support getting rid of basemap, but this can get us back with running tests at NERSC.

unique plt.axes for test

---

bin/user_metadata.sh
doc/changes.rst
py/desiutil/data/census.yaml
py/desiutil/setup.py
py/desiutil/test/make_testmaps.py
py/desiutil/test/test_install.py

This PR removes references to project/projectdirs.  Most of this code is rarely used.
*Do not merge yet.*  We still need to figure out what the new name of the cfs metadata file will be.

Remove references to project/projectdirs

---

bin/fix_permissions.sh
doc/changes.rst

This PR prevents `fix_permissions.sh` from running in or on a `$HOME` directory.
I wanted to get this into master, but I don't think we need to cut a new tag for this.

Check for HOME directory

---

doc/changes.rst
py/desiutil/install.py
py/desiutil/test/test_install.py

This PR adds nightwatch and desimeter to the list of known packages, and adds `-j 8` to the `make install` command for compiled codes so that they compile faster in parallel (spexec in particular).
Note: nightwatch doesn't actually support `python setup.py install` yet, but this gets a placeholder ready in desiInstall for if/when nightwatch is ready to be installed.

add nightwatch, desimeter, and parallel make

---

.travis.yml
doc/changes.rst
py/desiutil/test/test_install.py
py/desiutil/test/test_log.py

This PR fixes #144 by migrating tests to use `pytest` and `sphinx-build` instead of `python setup.py test` and `python setup.py build_sphinx`.
I'd like to issue a new tag after merging, so this can make it into a 20.6 release.

Replace python setup.py test

---

.gitignore
py/desiutil/test/test_install.py

This PR fixes #147 
The good news is that it appears http is now being comprehensively forwarded to https for desi.lbl.gov.  But the test was interpreting a redirect as a successful connection when it should have been a failure.

Use https to avoid redirect

---

requirements.txt

Recent healpy is incompatible with astropy 2.x but doesn't properly reflect that in its package requirements.  Pin to an old version of healpy for travis tests for now.  desispec and desisim had the same problem which was fixed by pinning their version of healpy for travis testing.
This is a temporary fix.  The plan going forward is:
* get all our packages working with astropy=4.x (and other updated packages) while still supporting astropy=2.x.  I'm actively working on this.
* make set of tags and a software release
* drop support for astropy 2.x for future work and update tests, requirements.txt etc to use more recent version.

pin healpy requirement for old astropy

---

py/desiutil/install.py
py/desiutil/modules.py

This PR makes desiInstall more robust to a non-standard `$DESICONDA` by filtering it through `os.path.normpath` before parsing it.  In particular the previous version interpreted `/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec//conda` as version '' (blank) instead of '20200801-1.4.0-spec' due to the double slash.
It also fixes a py3.8 SyntaxWarning about using `is not` instead `!=` when comparing a variable to a literal (prior syntax happens to work with cpython, but isn't guaranteed by the language syntax).  `blat is not None` is still ok, but `blat is not ""` raises a SyntaxWarning in py3.8.

desiconda normpath and fix 'is not' SyntaxWarning

---

doc/api.rst
doc/changes.rst
py/desiutil/test/test_timer.py
py/desiutil/timer.py

This PR adds a lightweight `desiutil.timer.Timer` utility class to standardize timing reports of pipeline steps.  It is intended for steps that take seconds to minutes, not for high-resolution profile timing of N>>1 functions.  e.g. in desispec pipeline steps I plan to track python startup, initial input, algorithm, and final output times.
Example usage with either `Timer.start(name)` and `Timer.stop(name)` or with a context manager `Timer.time(name)`:
```python
import time
from desiutil.timer import Timer
t = Timer()
t.start('blat')
time.sleep(0.1)
with t.time('input'):
time.sleep(0.1)
time.sleep(0.1)
t.stop('blat')
print(t.report())
```
Note that named timers can be nested and interleaved.  If run as a script `blat.py` this would produce:
```
TIMER-START:blat.py:6:<module>: Starting …
```

add Timer class to standardize algorithm timing reports

---

doc/changes.rst
py/desiutil/test/test_timer.py
py/desiutil/timer.py

This PR adds several features that I wanted when actually putting it into use in desispec:
* silent option: record timing, but don't print log messages, e.g. to record timing for multiple MPI ranks without having every rank blasting timing log messages.
* `calculate_stats` (like Ted's example from CMB-land suggested in the original Timer PR #151): combine multiple Timers into a report with min/max/mean/median of start/stop/duration.
* options to `start` and `stop` to set the time to use instead of `time.time()`, useful for recording timing of events that may have occurred before the timer was created, e.g. python startup and imports.
* `Timer.cancel` to discard a named timer that had been started.
I'll submit a companion desispec PR that uses these features, but this PR will need to be …

more Timer functionality

---

.travis.yml
doc/api.rst
doc/changes.rst
py/desiutil/redirect.py
py/desiutil/test/test_redirect.py

The unit tests are not yet working, since redirecting stdout actually breaks the unit test runner (which has a persistent handle to sys.stdout).  I am working on a unit test that runs the redirection in a subprocess.

Work on moving stdout / stderr redirection from desispec to desiutil

---

.github/workflows/python-package.yml
doc/changes.rst
py/desiutil/iers.py
py/desiutil/svn.py
py/desiutil/test/test_setup.py
requirements.txt

[Astropy 4.2 no longer has `astropy.erfa`](https://docs.astropy.org/en/stable/whatsnew/4.2.html#whatsnew-4-2-erfa), so ERFA warnings need to support the new package.
In addition, some unexpected interaction between very recent versions of `setuptools` and `disutils` were discovered, as more recent versions of Astropy bring in these more recent versions of `setuptools`.

Support recent astropy versions

---

doc/changes.rst
doc/desiInstall.rst
py/desiutil/install.py
py/desiutil/test/test_install.py

Our two hybrid python/C++ packages (fiberassign and specex) have now converted to using `python setup.py install` for installations, including compiling the C++ code.  This was creating a fake-failure problem for desiInstall which was noticing the `src/` directory and trying to run a non-existent Makefile.  This PR updates the installation code to use build type "py" OR "make" OR "src" but not "py" AND "src".  I left the "make" and "src" logic in place even though we don't have any packages using them now, but if the `setup.py` file is found it uses that and then moves on.
This also fixes a bug where if the `desiInstall --root ...`directory didn't exist at NERSC, the code was silently falling back to the default NERSC install location instead of warning the user that their requested …

install py or src not both; no silent installdir fallback

---

doc/changes.rst
py/desiutil/depend.py
py/desiutil/test/test_depend.py

This PR adds `desiutil.depend.mergedep` as a utility function to merge DEPNAMnn + DEPVERnn dependencies+versions from one header into another.  We messed this up with the blanc run by simply copying header keywords from one to the other, resulting in the same `DEPNAMnn` being listed more than once for different dependencies.  This `mergedep` function takes care of rearranging numbers as needed.  See the tests for examples.

add desiutil.depend.mergedep + tests

---

doc/changes.rst
doc/desiInstall.rst
py/desiutil/install.py
py/desiutil/modules.py

This PR closes #167.  In addition to a simple replacement of `python setup.py install` with the equivalent `pip install .`, this PR
* Updates the known packages.
* Begins preparation for the transition to Lmod-based modules.

Switch to pip install

---

doc/changes.rst
py/desiutil/install.py

This PR fixes #174 by changing the logic of how messages printed on STDERR are handled by `desiInstall`.  The new logic can be summarized by this snippet:
```python
if len(err) > 0:
#
#
if proc.returncode == 0:
message = ("Pip emitted messages on STDERR; these can probably be ignored:\n" +
err)
self.log.warning(message)
else:
message = ("Potentially serious error detected during pip installation:\n" +
err)
self.log.critical(message)
raise DesiInstallException(message)
```
@sbailey, I know you're out of the office.  Maybe @tskisner can take a quick look?  I think this will be pretty non-controversial though.

Ignore messages on STDERR unless there is a non-zero return code

---

py/desiutil/plots.py

This PR avoids a deprecation warning when using matplotlib 3.5:
```
pytest py/desutil/test
...
test/test_plots.py::TestPlots::test_plot_sky_binned
/global/common/software/desi/users/sjbailey/desiutil/py/desiutil/plots.py:718: MatplotlibDeprecationWarning: Auto-removal of grids by pcolor() and pcolormesh() is deprecated since 3.5 and will be removed two minor releases later; please call grid(False) first.
mesh = ax.pcolormesh(grid_ra, grid_dec,
```
However, I haven't looked into what is actually happening with turning the grid off and on, so I'd appreciate a check by someone who knows what a real-world output plot is supposed to look like with this code.  @weaverba137 @dkirkby ?
This is housecleaning for a 21.12 software release for Fuji, but is low priority in the big picture.

fix pcolormesh grid deprecation warning with matplotlib 3.5

---

doc/changes.rst
py/desiutil/depend.py
py/desiutil/test/test_depend.py

This PR addresses desihub/desispec#1077 by adding the following environment variables to the suite of dependencies added by `desiutil.depend.add_dependencies`:
* DESI_ROOT
* DESI_SPECTRO_DATA
* DESI_SPECTRO_REDUX
* SPECPROD
* DESI_SPECTRO_CALIB
* DESI_BASIS_TEMPLATES
* DESI_TARGET
* DESIMODEL
this expands the concept of "dependencies" to be not just code versions but also input directories.  This list can be overridden with `envvar_names` option analogous to pre-existing `module_names` option.
I will make a companion PR on desispec to make sure we call this for every `desispec.io.write*` function, but this PR doesn't need to wait for that.
@weaverba137 if you have a chance to take a look, please do, but I plan to merge later today when I get to the point of needing this for testing.

add_dependencies includes envvars

---

py/desiutil/install.py

Small update to add gpu_specter to the list of known packages.
Currently `desiInstall gpu_specter ...` correctly guesses what to do and logs a warning that it is guessing; this update just makes it so that it doesn't have to guess and thus doesn't log a harmless warning.

add gpu_specter to known packages

---

doc/changes.rst
doc/desiInstall.rst
py/desiutil/install.py
py/desiutil/test/test_install.py

This PR closes #186.
@sbailey, I've done one test so far, but I'd like to have more people testing this before merging.
On NERSC/perlmutter, desiutil/main already points to this branch.

[WIP] Add method for compiling code in a branch

---

.gitignore
doc/desiInstall.rst
py/desiutil/iers.py
py/desiutil/install.py
py/desiutil/modules.py
py/desiutil/test/test_iers.py
py/desiutil/test/test_install.py
py/desiutil/test/test_modules.py

This PR:
* Closes #192.
* Closes #194.
* Adds test coverage to other aspects of `desiInstall`.
Summarizing changes to `desiInstall`:
* Module files will always be installed world-read.
* Software files will be installed world-read, and user,group-read-only, unless:
- ``--no-world`` is specified, in which case world-read is *disabled*.
- A branch is installed, including `main`, in which case user-write is *enabled*.
* Internally, `fix_permissions.sh` is no longer used. In fact, no external scripts or unix commands are used to change permissions.

Update permission settings when installing

---

.github/workflows/python-package.yml
bin/annotate_fits
doc/api.rst
doc/changes.rst
doc/conf.py
py/desiutil/annotate.py
py/desiutil/test/test_annotate.py
setup.cfg

This PR addresses parts of #191, focussed on adding units to a `astropy.table.Table`.
Here's a simple test snippet:
```python
import os
import importlib.resources as ir
from astropy.table import Table
import desiutil.annotate as da
from desiutil.log import get_logger, DEBUG
da.log = get_logger(DEBUG)
csvFile = os.path.join(str(ir.files('desidatamodel')), 'data', 'column_descriptions.csv')
units, comments = da.csv_units(csvFile)
coadd = '/global/cfs/cdirs/desi/public/edr/spectro/redux/fuji/healpix/sv3/dark/99/9994/coadd-sv3-dark-9994.fits'
t = Table.read(coadd, hdu='FIBERMAP')
tt = da.annotate_table(t, units)  # tt is a copy of t; t is not supposed to be modified in this example.
```
TO DO:

Add units to a Table

---

py/desiutil/depend.py
py/desiutil/test/test_depend.py

This PR updates `desiutil.depend` to add support for removing DEPNAMnn/DEPVERnn dependencies:
* `removedep(header, name)`: remove a single dependency by name
* `remove_dependencies(header)`: remove all dependencies
This also required some updates to `getdep` and `iterdep` to not trip on dependencies that had been removed, resulting in non-contiguous DEPNAMnn counting.
This will be used by desihub/desispec#2121 which needs to remove DEPNAM/DEPVER keywords from individual file inputs while stacking them so that they don't get incorrectly merged by `astropy.table.vstack` logic which doesn't know about DEPNAMnn/DEPVERnn pairs.

add support for removing dependencies

---

.github/workflows/python-package.yml
doc/changes.rst
doc/index.rst
py/desiutil/setup.py
py/desiutil/test/test_setup.py
setup.cfg

This PR allows a wide variety of valid version strings to be parsed by `desiutil.setup.get_version()`.
While developing this, it was discovered that `desiutil.dust.ext_fitzpatrick()` requires `scipy`, but this requirement had never been explicitly listed. It appears that previously, one or more of astropy, healpy or matplotlib would bring in a dependency on scipy, but more recent versions do not have that dependency, so scipy has to be installed explicitly.

Add support for version string corner cases.

---

doc/changes.rst
py/desiutil/bitmask.py
py/desiutil/test/test_bitmask.py
setup.cfg

This PR fixes #218.
This should be tested with other packages such as desispec and desitarget before merging.

Support for mask bits in Numpy 2

---

doc/changes.rst
py/desiutil/bitmask.py
py/desiutil/test/test_bitmask.py
py/desiutil/test/test_setup.py

This PR fixes #220.
In #219, I think there was a miscommunication:
> I confirm that this fixes the desispec mask-related test failures when running with numpy 2.x, and also works with numpy 1.x.
I assumed that meant that all tests with desitarget, desispec, redrock, and any other package in the nightly desitest suite were succeeding. But that doesn't seem to be consistent with #220. But maybe that meant *only* desispec? Please clarify.
In any case, let's make sure that *every* package is happy with these changes before merging.

Support for NumPy scalars

---

doc/rtd-requirements.txt

This is a very minor PR that removes references to `urllib3<2` from `doc/rtd-requirements.txt`. `urllib3<2` is being flagged as a security vulnerability by GitHub, even though it is not part of active user code.

Remove unneeded requirements
